export type TranslateLanguage = {
  code: string
  name: string
}

// Idioma de origem do portal — deve vir sempre primeiro na lista.
export const SOURCE_LANGUAGE: TranslateLanguage = { code: 'pt', name: 'Português (original)' }

// Lista completa de idiomas suportados pelo Google Translate.
export const TRANSLATE_LANGUAGES: TranslateLanguage[] = [
  SOURCE_LANGUAGE,
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'es', name: 'Español' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'xh', name: 'isiXhosa' },
  { code: 'st', name: 'Sesotho' },
  { code: 'nso', name: 'Sepedi' },
  { code: 'ts', name: 'Xitsonga' },
  { code: 'sn', name: 'chiShona' },
  { code: 'ny', name: 'Chichewa' },
  { code: 'rw', name: 'Ikinyarwanda' },
  { code: 'so', name: 'Soomaali' },
  { code: 'am', name: 'አማርኛ (Amárico)' },
  { code: 'ha', name: 'Hausa' },
  { code: 'ig', name: 'Igbo' },
  { code: 'yo', name: 'Yorùbá' },
  { code: 'ar', name: 'العربية (Árabe)' },
  { code: 'he', name: 'עברית (Hebraico)' },
  { code: 'fa', name: 'فارسی (Persa)' },
  { code: 'ur', name: 'اردو (Urdu)' },
  { code: 'ps', name: 'پښتو (Pachto)' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'nl', name: 'Nederlands' },
  { code: 'pl', name: 'Polski' },
  { code: 'ro', name: 'Română' },
  { code: 'ru', name: 'Русский' },
  { code: 'uk', name: 'Українська' },
  { code: 'el', name: 'Ελληνικά' },
  { code: 'tr', name: 'Türkçe' },
  { code: 'cs', name: 'Čeština' },
  { code: 'sk', name: 'Slovenčina' },
  { code: 'sl', name: 'Slovenščina' },
  { code: 'hr', name: 'Hrvatski' },
  { code: 'sr', name: 'Српски' },
  { code: 'bs', name: 'Bosanski' },
  { code: 'bg', name: 'Български' },
  { code: 'mk', name: 'Македонски' },
  { code: 'sq', name: 'Shqip' },
  { code: 'hu', name: 'Magyar' },
  { code: 'fi', name: 'Suomi' },
  { code: 'sv', name: 'Svenska' },
  { code: 'da', name: 'Dansk' },
  { code: 'no', name: 'Norsk' },
  { code: 'is', name: 'Íslenska' },
  { code: 'et', name: 'Eesti' },
  { code: 'lv', name: 'Latviešu' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'ga', name: 'Gaeilge' },
  { code: 'gd', name: 'Gàidhlig' },
  { code: 'cy', name: 'Cymraeg' },
  { code: 'ca', name: 'Català' },
  { code: 'gl', name: 'Galego' },
  { code: 'eu', name: 'Euskara' },
  { code: 'mt', name: 'Malti' },
  { code: 'lb', name: 'Lëtzebuergesch' },
  { code: 'fy', name: 'Frysk' },
  { code: 'co', name: 'Corsu' },
  { code: 'la', name: 'Latina' },
  { code: 'eo', name: 'Esperanto' },
  { code: 'hy', name: 'Հայերեն (Arménio)' },
  { code: 'az', name: 'Azərbaycan' },
  { code: 'ka', name: 'ქართული (Georgiano)' },
  { code: 'kk', name: 'Қазақ тілі' },
  { code: 'ky', name: 'Кыргызча' },
  { code: 'uz', name: 'Oʻzbek' },
  { code: 'tg', name: 'Тоҷикӣ' },
  { code: 'tk', name: 'Türkmen' },
  { code: 'mn', name: 'Монгол' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'ta', name: 'தமிழ் (Tâmil)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'ml', name: 'മലയാളം (Malaiala)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Canarês)' },
  { code: 'gu', name: 'ગુજરાતી (Gujarati)' },
  { code: 'mr', name: 'मराठी (Marata)' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ (Punjabi)' },
  { code: 'ne', name: 'नेपाली (Nepalês)' },
  { code: 'si', name: 'සිංහල (Cingalês)' },
  { code: 'my', name: 'မြန်မာ (Birmanês)' },
  { code: 'km', name: 'ខ្មែរ (Khmer)' },
  { code: 'lo', name: 'ລາວ (Lao)' },
  { code: 'th', name: 'ไทย (Tailandês)' },
  { code: 'vi', name: 'Tiếng Việt' },
  { code: 'id', name: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Bahasa Melayu' },
  { code: 'tl', name: 'Filipino' },
  { code: 'jv', name: 'Basa Jawa' },
  { code: 'su', name: 'Basa Sunda' },
  { code: 'zh-CN', name: '中文（简体）' },
  { code: 'zh-TW', name: '中文（繁體）' },
  { code: 'ja', name: '日本語' },
  { code: 'ko', name: '한국어' },
  { code: 'mi', name: 'Te Reo Māori' },
  { code: 'sm', name: 'Gagana Sāmoa' },
  { code: 'haw', name: 'ʻŌlelo Hawaiʻi' },
  { code: 'yi', name: 'ייִדיש (Iídiche)' },
  { code: 'af', name: 'Afrikaans' },
  { code: 'mg', name: 'Malagasy' },
  { code: 'ee', name: 'Eʋegbe' },
  { code: 'ak', name: 'Twi' },
  { code: 'lg', name: 'Luganda' },
  { code: 'om', name: 'Oromoo' },
  { code: 'ti', name: 'ትግርኛ (Tigrínia)' },
  { code: 'sd', name: 'سنڌي (Sindi)' },
  { code: 'ug', name: 'ئۇيغۇرچە (Uigur)' },
  { code: 'ku', name: 'Kurdî' },
  { code: 'ckb', name: 'کوردیی ناوەندی' },
  { code: 'ht', name: 'Kreyòl Ayisyen' },
  { code: 'qu', name: 'Runasimi (Quíchua)' },
  { code: 'ay', name: 'Aymar aru' },
  { code: 'gn', name: 'Avañeʼẽ (Guarani)' },
]
